include make-rules/common.mk # make sure include common.mk at the first include line
include make-rules/tools.mk
include make-rules/golang.mk

## tools: install dependent tools.
.PHONY: tools
tools:
	@$(MAKE) tools.install